server:
  port: 80
logging:
  file: log.log.txt

generator:
  conf:
    # 数据库类型与Java类型的映射
    tinyint: Integer
    smallint: Integer
    mediumint: Integer
    int: Integer
    integer: Integer

    bigint: Long

    float: Float

    double: Double

    decimal: BigDecimal

    bit: Boolean

    char: String
    varchar: String
    tinytext: String
    text: String
    mediumtext: String
    longtext: String

    date: Date
    datetime: Date
    timestamp: Date
ROOT: project
JAVA_ROOT: ${ROOT}.src.main.java
RESOUCRCES: ${ROOT}.src.main.resources
template:
  conf:
   Controller.java.vm: ${JAVA_ROOT}.packageName.controller.classNameController:java
   Service.java.vm: ${JAVA_ROOT}.packageName.service.classNameService:java
   ServiceImpl.java.vm: ${JAVA_ROOT}.packageName.service.impl.classNameServiceImpl:java
   Mapper.java.vm: ${JAVA_ROOT}.packageName.mapper.classNameMapper:java
   Provider.java.vm: ${JAVA_ROOT}.packageName.mapper.provider.classNameProvider:java
   PO.java.vm: ${JAVA_ROOT}.packageName.entity.className:java
   Application.java.vm: ${JAVA_ROOT}.packageName.Application:java
   application.yml.vm: ${RESOUCRCES}.application:yml
   banner.txt.vm: ${RESOUCRCES}.banner:txt
   pom.xml.vm: ${ROOT}.pom:xml

spring:
  #邮件服务配置
  mail:
    host: smtp.126.com
    username: myjnxj@126.com
    password:
    default-encoding: UTF-8
  #aop配置
  aop:
    auto: true
    proxy-target-class: true
mail:
  fromMail:
    addr: myjnxj@126.com
