spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wechat?useUnicode=true&characterEncoding=utf-8&userSSL=false&serverTimezone=GMT%2B8
    username: root
    password: Jun6311158
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT1FROMDUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,log4j
    logSlowSql: true
    platform: mysql
server:
  port: 8080
logging:
  file: log/log.txt

generator:
  conf:
    # 数据库类型与Java类型的映射
    tinyint: Integer
    smallint: Integer
    mediumint: Integer
    int: Integer
    integer: Integer

    bigint: Long

    float: Float

    double: Double

    decimal: BigDecimal

    bit: Boolean

    char: String
    varchar: String
    tinytext: String
    text: String
    mediumtext: String
    longtext: String

    date: Date
    datetime: Date
    timestamp: Date